name: Build SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get -y install --no-install-suggests libapr1-dev libxerces-c-dev libicu-dev openjdk-17-jdk-headless build-essential pkgconf autoconf file libtool m4 automake swig4.0 libpython3-dev libperl-dev
      
    - name: Build SDK
      run: |
        cd $GITHUB_WORKSPACE
        ./autogen.sh
        mkdir /usr/local/uimacpp
        mkdir /usr/local/uimacpp/desc
        mkdir /usr/local/uimacpp/scripts
        mkdir /usr/local/uimacpp/ae
        ./configure --prefix=/usr/local/uimacpp --without-activemq --with-jdk=/usr/lib/jvm/java-17-openjdk-amd64/
        make -j4
        make install
        make check
        
    - name: Configure pythonnator
      run: |
        echo '/usr/local/uimacpp/lib' | sudo tee -a /etc/ld.so.conf.d/uimacpp.conf
        sudo ldconfig
        cd /uima-cpp/scriptators/python
        UIMACPP_HOME=/usr/local/uimacpp make
        sudo cp _pythonnator.so /usr/local/uimacpp/lib
        sudo ln -s ../lib/_pythonnator.so /usr/local/uimacpp/scripts/_pythonnator.so
        sudo ln -s ../scripts/_pythonnator.so /usr/local/uimacpp/lib/libpythonnator.so
        sudo cp Pythonnator.xml /usr/local/uimacpp/desc/
        sudo cp ae.py pythonnator.py /usr/local/uimacpp/scripts/
        
    - name: Configure perltator
      run: |
        cd /uima-cpp/scriptators/perl
        UIMACPP_HOME=/usr/local/uimacpp make
        sudo cp perltator.so /usr/local/uimacpp/lib
        sudo ln -s perltator.so /usr/local/uimacpp/lib/libperltator.so
        sudo cp Perltator.xml /usr/local/uimacpp/desc/
        sudo cp ae.pl perltator.pm /usr/local/uimacpp/scripts/
        
    - name: Generate image with installed files
      run: |
        sudo apt-get update
        sudo apt-get -y install --no-install-suggests libapr1 libxerces-c3.2 libicu72 libpython3.11 libperl5.36
        echo '/usr/local/uimacpp/lib' | sudo tee -a /etc/ld.so.conf.d/uimacpp.conf
        sudo ldconfig
        sudo cp -r /usr/local/uimacpp /usr/local/
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64 -t uimacpp_image .
